### ISSUE TITLE
build issue with tor Ubuntu 16.04

### ISSUE THREAD

**Issue by crackfoo** [noirofficial/noir#11]
Hi, 

trying to build latest master it fails on tor section:

make[1]: Entering directory '/usr/local/src/noir/src/tor'
  CCLD     src/or/tor
src/or/libtor.a(main.o): In function `tor_main':
main.c:(.text+0x7f79): undefined reference to `evutil_secure_rng_set_urandom_device_file'
src/common/libor-event.a(compat_libevent.o): In function `tor_gettimeofday_cache_clear':
compat_libevent.c:(.text+0x840): undefined reference to `event_base_update_cache_time'
collect2: error: ld returned 1 exit status
Makefile:4512: recipe for target 'src/or/tor' failed
make[1]: *** [src/or/tor] Error 1
make[1]: Leaving directory '/usr/local/src/noir/src/tor'
Makefile:3322: recipe for target 'all' failed
make: *** [all] Error 2

dpkg -l |grep libevent
ii  libevent-2.0-5:amd64                   2.0.21-stable-2ubuntu0.16.04.1             amd64        Asynchronous event notification library
ii  libevent-core-2.0-5:amd64              2.0.21-stable-2ubuntu0.16.04.1             amd64        Asynchronous event notification library (core)
ii  libevent-dev                           2.0.21-stable-2ubuntu0.16.04.1             amd64        Asynchronous event notification library (development files)
ii  libevent-extra-2.0-5:amd64             2.0.21-stable-2ubuntu0.16.04.1             amd64        Asynchronous event notification library (extra)
ii  libevent-openssl-2.0-5:amd64           2.0.21-stable-2ubuntu0.16.04.1             amd64        Asynchronous event notification library (openssl)
ii  libevent-pthreads-2.0-5:amd64          2.0.21-stable-2ubuntu0.16.04.1             amd64        Asynchronous event notification library (pthreads)

Any ideas?

Thanks

**Comment by flo071** [comment]
Hi thank you for the detailed information, i was never able to reproduce this issue, but there is a workaround found by @pool2mine. 

you need to do this at the configure step:
./configure LIBS="-lcap -lseccomp"
