### ISSUE TITLE
Windows Noir Wallet consuming to mutch CPU and Memory

### ISSUE THREAD

**Issue by jmg19** [noirofficial/noir#2]
Noir Wallet is consuming half of CPU resourses and 700MB of memory.
I think it is to mutch if we compare with the old Zoin Wallet.
![wallet-consuming-to-mutch](https://user-images.githubusercontent.com/7068235/46921950-fc35f100-cff9-11e8-9225-8fc6bcdf87e4.png)

**Comment by jmg19** [comment]
Yes it was.

**Comment by flo071** [comment]
i have never experienced this after reindex or sync was done. is this still the case in our latest 1.0.0.1 release?

**Comment by jmg19** [comment]
Sorry for the late reply, but I was waiting for my updated wallet to sync.
The problem does not occur in this new version.
Thanks Team ;)
