### ISSUE TITLE
Inspect and fix potential memory leak

### ISSUE THREAD

**Issue by flo071** [noirofficial/noir#28]
Reported by users on discord.

Walllet uses way too much RAM when staking.

**Comment by mmartain** [comment]
Here too. 

Latest version.
Windows 10

Currently using about 3153MB ram

**Comment by flo071** [comment]
Wallet Version: v2.1.0.2-da4de91
OS: Linux Mint 19.2

Wallet with staking enabled uses 13.2% of memory.

**Comment by flo071** [comment]
No new reports so far. Closing for now. (Can be reopened, if new cases come)
