### ISSUE TITLE
Wallet ability to run on MacOS 10.12 Sierra

### ISSUE THREAD

**Issue by JDgroover** [noirofficial/noir#8]
Wallet currently requires 10.13 or later

I have 10.12 and unable to go up as other software incompatibilities

flo071 told me he is working on this, thought I'd put it here to make it official, cheers

**Comment by flo071** [comment]
Resolved, build is available here: https://github.com/noirofficial/noir/releases/download/v1.0.0.3/noir-qt-1.0.0.3-macOS-10.12.dmg
