### ISSUE TITLE
Wallet install crashes 

### ISSUE THREAD

**Issue by pool2mine** [noirofficial/noir#9]
CXXLD    noird
tor/src/common/libor.a(compat.o): In function `drop_capabilities':
compat.c:(.text+0xed): undefined reference to `cap_get_proc'
compat.c:(.text+0x101): undefined reference to `cap_clear'
compat.c:(.text+0x116): undefined reference to `cap_set_flag'
compat.c:(.text+0x12e): undefined reference to `cap_set_flag'
compat.c:(.text+0x149): undefined reference to `cap_set_flag'
compat.c:(.text+0x151): undefined reference to `cap_set_proc'
compat.c:(.text+0x15b): undefined reference to `cap_free'
tor/src/common/libor.a(compat.o): In function `have_capability_support':
compat.c:(.text+0x2685): undefined reference to `cap_get_proc'
compat.c:(.text+0x2694): undefined reference to `cap_free'
tor/src/common/libor.a(sandbox.o): In function `sb_kill':
sandbox.c:(.text+0x1fe): undefined reference to `seccomp_rule_add'
tor/src/common/libor.a(sandbox.o): In function `sb_ioctl':
sandbox.c:(.text+0x271): undefined reference to `seccomp_rule_add'
tor/src/common/libor.a(sandbox.o): In function `sb_socketpair':
sandbox.c:(.text+0x31a): undefined reference to `seccomp_rule_add'
tor/src/common/libor.a(sandbox.o): In function `sb_stat64':
sandbox.c:(.text+0x3dc): undefined reference to `seccomp_rule_add'
tor/src/common/libor.a(sandbox.o): In function `sb_poll':
sandbox.c:(.text+0x4a7): undefined reference to `seccomp_rule_add'
tor/src/common/libor.a(sandbox.o):sandbox.c:(.text+0x51e): more undefined references to `seccomp_rule_add' follow
tor/src/common/libor.a(sandbox.o): In function `sandbox_init':
sandbox.c:(.text+0x33ba): undefined reference to `seccomp_init'
sandbox.c:(.text+0x3500): undefined reference to `seccomp_release'
sandbox.c:(.text+0x35ce): undefined reference to `seccomp_rule_add'
sandbox.c:(.text+0x3634): undefined reference to `seccomp_rule_add'
sandbox.c:(.text+0x3712): undefined reference to `seccomp_rule_add'
sandbox.c:(.text+0x37d7): undefined reference to `seccomp_rule_add'
sandbox.c:(.text+0x38d3): undefined reference to `seccomp_rule_add'
sandbox.c:(.text+0x392f): undefined reference to `seccomp_load'
sandbox.c:(.text+0x394b): undefined reference to `seccomp_release'
collect2: error: ld returned 1 exit status
Makefile:3288: recipe for target 'noird' failed
make[2]: *** [noird] Error 1
make[2]: Leaving directory '/home/server2/noir/src'
Makefile:7854: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/server2/noir/src'
Makefile:688: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by pool2mine** [comment]
i am trying to move Noir Wallet to a new server but it keeps crashing, on that server i am running XVG and GXX wallets, can it be conflicting?

**Comment by flo071** [comment]
looks like the build is failing. it should not have any problems with having gxx or xvg wallets installed. please make sure you installed every dependency mentioned in the readme.

**Comment by flo071** [comment]
Issue could not be reproduced.

**Comment by pool2mine** [comment]
./autogen.sh
./configure LIBS="-lcap -lseccomp"
make

this is a workaround to my problem, hope it will help others
